Load more
qri-io/2017-frontend pull request #102
Opened 2017-10-25 21:09 UTC by ramfox

At the end of a List there a LoadMore component. It will show as a:
- Load More button or
- an End of list label or
- a loading spinner

* [x] Queries
* [x] Search
* [x] Peers
* [x] Datasets

2017-10-28 13:48 UTC, ramfox commented
- **Peers**
  setting the page number doesn't effect what returns
- **Datasets**
   sometimes you get repeat entries returned, even if the page number is different
- **Datasets Search**
   pageSize doesn't have an effect

2017-10-28 14:48 UTC, ramfox commented
- Perhaps we don't need to say 'end of list,' maybe we just leave it blank and people will assume it's the end?
- need to fix loading spinner for search

2017-10-28 16:11 UTC, b5 commented
I'd vote for just leaving the end of lists blank, but being sure to add a fair amount of whitespace below the final element in any list so users can clearly see that no new results are coming.

2017-10-30 12:11 UTC, b5 requested changes
Looks good! Added like 5 mins worth of nitty-gritty

2017-10-30 12:11 UTC, b5 commented on app/components/Queries.js
> +    console.log(this.props.queries)
can you clean up this logging?

2017-10-30 12:11 UTC, b5 commented on app/components/Datasets.js
> +    console.log(height)
more logging cleanup

2017-10-30 12:11 UTC, b5 commented on app/components/LoadMore.js
> +      button: {
Brighten up the button & remove the left margin to left-justify for now? Either that or `margin: 15px auto` to center the button, my preference would be left justification for the time being

2017-10-30 22:36 UTC, ramfox commented on app/components/LoadMore.js
> +      button: {
Let me know what you think of the changes I made :) Can make it a different color, but thought this might be a good option.

2017-10-30 22:39 UTC, b5 approved these changes
🇼🇸 🍶 ♐️

2017-10-30 22:40 UTC, merged

2017-10-31 14:32 UTC, ramfox commented
closes #79