Cleaning and Syncing PropTypes
qri-io/2017-frontend pull request #35
Opened 2017-09-19 21:35 UTC by ramfox

- Going through each component and making sure the PropTypes cover all the props used in the component. #31
- Starting to create a common propTypes directory (example can be seen in /components/DataTable.js, `fields` is of propType `fieldsProps`. `fieldsProps` was imported from /propTypes/datasetProps. issue #32

2017-09-19 21:36 UTC, ramfox commented
Questionssssss :)

- **DateInput.js**
    *is `onChange` required in this case? function is passed to render, but will it break if `onChange` is undefined? probs, right?*
    *`name` is required, but default doesn't specify*
- **KeyValueForm.js**
    *bunch of commented out code and proptypes, add a TODO remove?*
    *can't tell what `this.props.data` is, also `KeyValueForm` not used anywhere so no clues there.*
    *would love explaination of `this.onChangeKey`, where there is no function declared as such*
- **KeyValueInput.js**
    *not going to take away something you said is required, but why is `onChangeValue` required?*
- **MetadataForm.js**
    *Where is this 'data' and 'validation' coming from, and how can I find out what the shape is?*
    `data` - title, description, theme, keyword, modified, issued, identifier, accessLevel, license, language, landingPage
    `validation` - title, description, 
    *Why is `onChange`, `onCancel` required?*
- **MonthCalendar.js**
    *all these checking `typeof` stuff, can I take out now that `propTypes` is here*
    *would love to know if I did the `isRequired` right*
- **TimePicker.js**
    *also has this type checking stuff*
    *lots of checking stuff, can I remove?*
    *`isRequired` check here for onChange, pretty sure it `isRequried`*
- **ChangeItem.js**
    *what is `data` here?*

2017-09-21 15:01 UTC, b5 requested changes
Nice! Just a few pointers to cleanup, then let's get this merged.

2017-09-21 15:01 UTC, b5 commented on src/js/components/BarChart.js
> +import React { PropTypes } from 'react'
missing comma, should be `import React, { PropTypes } from 'react'`

2017-09-21 15:01 UTC, b5 commented on src/js/components/DataTable.js
> +  data: PropTypes.arrayOf(PropTypes.array),
This is lovely. Nice addition

2017-09-21 15:01 UTC, b5 commented on src/js/components/form/Clock.js
> +      const value = this.props.value
should favour destructuring here `const { value } = this.props`

2017-09-21 15:01 UTC, b5 commented on src/js/components/form/Clock.js
> +      const value = this.props.value
favour destructuring

2017-09-21 15:01 UTC, b5 commented on src/js/components/form/ValidInput.js
> +  // an error message to displacy
*display

2017-09-21 15:01 UTC, b5 commented on src/js/components/form/ValidLicenseInput.js
> +  // an error message to displacy
*display

2017-09-21 15:01 UTC, b5 commented on src/js/components/form/ValidSelect.js
> +  error: undefined,
can be removed, as the "default" is already `undefined`

2017-09-21 15:09 UTC, b5 approved these changes

2017-09-21 15:10 UTC, merged